config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :geniuses, only: [:index, :show, :new, :create, :destroy] do
    resources :lectures, only: [:create, :destroy]
    resources :photos, only: [:new, :create]
  end
  resources :lectures, only: [:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genius.rb
class Genius < ApplicationRecord
  validates :name, presence: true
  validates :cost, presence: true
  validates :year, presence: true
  belongs_to :user
  has_many :lectures, dependent: :destroy
  has_many :photos, dependent: :destroy

  scope :with_photo, -> { joins(:photos).where("photos.genius_id IS NOT NULL").distinct }
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  validates :start_time, presence: true
  validates :end_time, presence: true
  belongs_to :genius
  belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :genius
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :email, presence: true
  has_many :genius
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/geniuses_controller.rb
class GeniusesController < ApplicationController
  before_action :set_genius, only: [:show, :increment_ig, :destroy]
  def index
    @geniuses = Genius.with_photo.order(iq: :desc)
  end

  def show
    # @genius = Genius.find(params[:id])
    @lecture = Lecture.new
  end

  def show_my
    @my_geniuses = Genius.where(user_id: current_user).order(name: :asc)
  end

  def show_my_bookings
    @my_bookings = Lecture.where(user_id: current_user)
  end

  def increment_ig
    @genius.iq += 1
    @genius.save
  end

  def new
    @photo = Photo.new
    @genius = Genius.new
    show_my
    show_my_bookings
  end

  def create
    @genius = Genius.new(genius_params)
    @genius.user = current_user
    # if @genius.save
    #   redirect_to new_genius_path
    # else
    #   render :new
    # end
    if @genius.save
      respond_to do |format|
        format.html { redirect_to new_genius_path }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js  # <-- idem
      end
    end
  end

  def destroy
    # @genius = Genius.find(params[:id])
    @genius.destroy
    redirect_to new_genius_path
  end

  private

  def set_genius
    @genius = Genius.find(params[:id])
  end

  def genius_params
    params.require(:genius).permit(:name, :year, :category, :description, :cost, :iq)
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: [:destroy]

  def create
    @lecture = Lecture.new(lecture_params)
    @genius = Genius.find(params[:genius_id])
    @lecture.genius = @genius
    @lecture.user = current_user
    if @lecture.save
      redirect_to genius_path(@genius)
    else
      render 'geniuses/show'
    end
  end

  def destroy
    @lecture.destroy
    redirect_to new_genius_path
  end

  private

  def set_lecture
    @lecture = Lecture.find(params[:id])
  end

  def lecture_params
    params.require(:lecture).permit(:start_time, :end_time)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	layout 'dashboard'
  def home
    @geniuses = Genius.first(3)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @photo = Photo.new(photo_params)
    @genius = Genius.find(params[:genius_id])
    @photo.genius = @genius
    if @photo.save
      redirect_to new_genius_path
    else
      render 'geniuses/show'
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/geniuses/create.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.querySelector('#new_genius');
  newReviewForm.innerHTML = innerHTML;
}


function addGenius(reviewHTML) {
  const reviews = document.getElementById('list-all-my-geniuses');
  reviews.insertAdjacentHTML('afterbegin', reviewHTML);
}

<% if @genius.errors.any? %>
  refreshForm('<%= j render "shared/form-genius", genius: @genius %>');
<% else %>
  refreshForm('<%= j render "shared/form-genius", genius: @genius %>');
  addGenius('<%= j render "shared/list-my-geniuses", genius: @genius %>');
<% end %>

app/views/geniuses/index.html.erb
  <div class="container">
    <h1>Genius Thinkers</h1>
    <div class="row">
      <% @geniuses.each do |genius| %>
        <%= render 'shared/cards', genius: genius%>
      <% end %>
    </div>
  </div>

app/views/geniuses/new.html.erb
<div class="container">
  <div class="d-flex justify-content-around">
    <div class="form-genius">
      <h2 class="text-center">Add a Genius</h2>
      <%= render 'shared/form-genius', genius: @genius %>
    </div>
    <div class="list-bookings">
       <%= render 'shared/list-bookings', my_bookings: @my_bookings %>
    </div>
  </div>
  <br>
  <br>
  <div>
    <h2 class="text-center">My Geniuses</h2>
    <ul class="list-scroll" id="list-all-my-geniuses">
      <% @my_geniuses.each do |genius| %>
      <%= render 'shared/list-my-geniuses', genius: genius, photo: @photo %>
      <% end %>
    </ul>
  </div>
</div>

app/views/geniuses/show.html.erb
<!-- Carousel implementation -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-container">
    <div class="carousel-inner">
     <% @genius.photos.each_with_index do |photo, i| %>
     <div class="carousel-item <%= "active" if i == 0  %>">
      <%= cl_image_tag photo.photo%>
    </div>
    <% end %>
  </div>
</div>
</div>
</div>

<!-- Booking form for Genius -->
<div class="container show-container">
  <div class="form_card">
    <div class="text-description">
      <%= render 'shared/text-description', genius: @genius%>
    </div>
  </div>
<div class="form-wrapper form_card">
  <h2>Book a lecture </h2>
  <%= render 'shared/form-lecture', genius: @genius, lecture: @lecture %>
</div>
</div>
<!-- </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Genius Rental</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Genius Rental</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar_home'%>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="body-color">

   <div class="home-banner">
    <!-- <h1>Geniuses through history</h1> -->
  </div>
  <br>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-10"><h4>
        <%= "Like great beauty, great intelligence can be a blessing or a curse to those who possess it. Sometimes the smartest among us live the most difficult lives. " %>
        </h4>
      </div>
    </div>
    <div class="format-style">
    <div class="format-outer">
      <div>
        <div class="format-inner">
          <div class="format-inner2">
            <div class="format-inner3">
              <div class="format-inner4">
                <div class="format-inner5">
                  <div class="format-inner6">
                    <h3>
                      <div>Explore holograms</div>
                    </h3>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div>

    <div class="container">
      <div class="row">
        <% @geniuses.each do |genius| %>
          <%= render 'shared/card-product', genius: genius%>
        <% end %>
      </div>
    </div>

  </div>

  </div>

  <br>
  <br>
    <h3>
        <div>Introducing Geniuses throughout history</div>
    </h3>
    <br><br>
    <%= render 'shared/banner'%>
  </div>

  <%= render 'shared/footer'%>
</div>

app/views/shared/_banner.html.erb
<%= link_to geniuses_path do %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path "heads.jpg", alt: "alttext" %>)">
    Explore
  </div>
<% end %>

app/views/shared/_card-product.html.erb
<div class="col-lg-4">
  <%= link_to genius_path(genius) do %>
    <div class="card-product">
      <%= cl_image_tag genius.photos.first.photo, crop: :fill, gravity: :face %>
      <div class="card-product-infos">
        <h2><%= genius.name %></h2>
        <p><%= genius.description[0..50] %>...</p>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_cards.html.erb
<div class="col-sm-4">
   <%= link_to genius_path(genius) do %>
  <div class="card-trip card-trip-width">
    <%= cl_image_tag(genius.photos.first.photo, width: 250, height: 150, crop: :thumb, gravity: :face)%>
    <div class="card-trip-infos">
      <div>
        <h2><%= genius.name %></h2>
        <small><%= genius.category.capitalize %></small>

      </div>


      <p class="card-trip-pricing"><i class="far fa-lightbulb"></i><%= genius.iq%></p>
    </div>

  </div>
<% end %>
  </div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Geniuses <i class="fas fa-heart"></i> IQ
  </div>
</div>

app/views/shared/_form-genius.html.erb
<div class="form_card_new">
  <%= simple_form_for genius, remote: true do |f| %>
    <%= f.input :name %>
    <%= f.input :year %>
    <%= f.input :category, placeholder: 'Write the name of Genius category'%>
    <%= f.input :description, as: :text, placeholder: 'Add the information describing your Genius here..' %>
    <%= f.input :cost, as: :integer %>
    <%= f.input :iq, as: :integer %>
    <%= f.submit "Summon a Genius to your team", class: "button_cust" %>
  <% end %>
</div>

app/views/shared/_form-homepage.html.erb
<%= simple_form_for (geniuses) do |f| %>
  <%= f.input :start_time, as: :datetime %>
  <%= f.submit "Book a Lecture", class: "button_cust" %>
<% end %>

app/views/shared/_form-lecture.html.erb
<%= simple_form_for ([genius, lecture]) do |f| %>
      <%= f.input :start_time, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :end_time, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Book a Lecture", class: "button_cust" %>
    <% end %>

app/views/shared/_list-bookings.html.erb
<h2 class="text-center">My booked lectures</h2>
<ul class="list-scroll ">
<% my_bookings.each do |lecture| %>
  <div class="form_card_new">
  <li>
    <div class="d-flex justify-content-between">
      <div>
        <h3><%=lecture.genius.name %> </h3>
      </div>
      <div>
        <%= link_to 'Delete Booking', lecture_path(lecture), method: :delete, :class => "button_cust" %>
      </div>
    </div>
      <p>Start Time: <%= lecture.start_time%></p>
      <p>End Time: <%= lecture.end_time %></p>
  </li>
  </div>
<% end %>
</ul>

app/views/shared/_list-my-geniuses.html.erb
  <div class="form_card_new">
    <li>
      <div class="list-header-button">
        <h3><%= genius.name %></h3>
        <%= link_to 'Go to Genius', genius_path(genius), :class => "button_cust_genius" %>
      </div>
      <p><%= genius.category.capitalize %></p>
      <small><%= genius.description%></small>
      <br>
      <br>
      <div class="d-flex justify-content-between">
        <div class="list-delete-div">

          <%= link_to 'Delete Genius', genius_path(genius), method: :delete, :class => "button_cust" %>
        </div>
        <div>
          <%= simple_form_for([genius, Photo.new]) do |f| %>
          <div>
            <%= f.input :photo %>
          </div>
          <div>
            <%= f.input :photo_cache, as: :hidden %>
          </div>
          <div>
            <%= f.button :submit, "Add", class: "button_cust" %>
          </div>
          <% end %>
        </div>
      </div>
    </li>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-grent">
  <%= link_to "/", class: "navbar-brand" do %>
  <%= image_tag "logo_grey.png", class: "border-radius"%>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Find Geniuses", geniuses_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "ludvig_londos.png", class: "avatar avatar-navbar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", new_genius_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Sign-up", new_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar2.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
  <%= image_tag "logo_grey.png", class: "border-radius"%>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Find Geniuses", "geniuses", id: "search-nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "ludvig_londos.png", class: "avatar avatar-navbar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "View my bookings", new_genius_path, class: "dropdown-item" %>
            <%= link_to "Add a Genius", new_genius_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Sign-up", new_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_home.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-home">
  <%= link_to "/", class: "navbar-brand" do %>
  <%= image_tag "logo_grey.png", class: "border-radius"%>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Find Geniuses", "geniuses", class: "nav-link", id: "search-nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "ludvig_londos.png", class: "avatar avatar-navbar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", new_genius_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Sign-up", new_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_text-description.html.erb
<h2><%= @genius.name %></h2>
<h3>Born in <%= @genius.year %></h3>
<h3><%= @genius.category.capitalize %></h3>
<p><%= @genius.description %></p>
<div class="d-flex justify-content-around">
  <div>
  <i class="fas fa-dollar-sign"></i><%= @genius.cost %>
  </div>
  <div>
  <i class="far fa-lightbulb"></i><%= @genius.iq %>
  </div>
</div>